// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-BQPeeaKxMQXe22d9Z0HDHnnXAwAkjNI',
    appId: '1:714695237258:web:51dc6c0aafbce4c89bd773',
    messagingSenderId: '714695237258',
    projectId: 'my-todo-list-9ad09',
    authDomain: 'my-todo-list-9ad09.firebaseapp.com',
    storageBucket: 'my-todo-list-9ad09.appspot.com',
    measurementId: 'G-TPB1VL8H9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6a4JoUNpsGVnC1I0fN788q-H2wRB3hEk',
    appId: '1:714695237258:android:8e6946e072489aaa9bd773',
    messagingSenderId: '714695237258',
    projectId: 'my-todo-list-9ad09',
    storageBucket: 'my-todo-list-9ad09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsfKUbvLbqomd44u_cDmQh4Z6sP9dlSz4',
    appId: '1:714695237258:ios:f0dc69254f6d60829bd773',
    messagingSenderId: '714695237258',
    projectId: 'my-todo-list-9ad09',
    storageBucket: 'my-todo-list-9ad09.appspot.com',
    iosBundleId: 'com.example.ch11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsfKUbvLbqomd44u_cDmQh4Z6sP9dlSz4',
    appId: '1:714695237258:ios:0782403739312b109bd773',
    messagingSenderId: '714695237258',
    projectId: 'my-todo-list-9ad09',
    storageBucket: 'my-todo-list-9ad09.appspot.com',
    iosBundleId: 'com.example.ch11.RunnerTests',
  );
}
